[build]
# rustflags = ["-Ctarget-feature=-sse,-sse2,-ssse3,-sse4.1,-sse4.2,-avx,-avx2,-avx512f"]
# rustflags = ["-Ctarget-feature=+sse,+sse2,+ssse3,+sse4.1,+sse4.2,-avx,-avx2,-avx512f"]
# rustflags = ["-Ctarget-feature=+sse,+sse2,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,-avx512f"]
# rustflags = ["-Ctarget-feature=+sse,+sse2,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+avx512f"]
rustflags = ["-Ctarget-cpu=native", "-Ctarget-feature=-prefer-256-bit,-prefer-128-bit"]